apiVersion: apps/v1
kind: Deployment
metadata:
  name: primenumber-service-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: primenumber-service
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
        sidecar.istio.io/logLevel: "info"
      labels:
        app: primenumber-service
        version: v1
    spec:
      containers:
        - name: primenumber-service
          image: cbagade/primenumber-app:v14
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9080
          env:
            - name: VERSION
              value: "v1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: primenumber-service-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: primenumber-service
      version: v2
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
        sidecar.istio.io/logLevel: "info"
      labels:
        app: primenumber-service
        version: v2
    spec:
      containers:
        - name: primenumber-service
          image: cbagade/primenumber-app:v14
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9080
          env:
            - name: VERSION
              value: "v2"
---
apiVersion: v1
kind: Service
metadata:
  name: primenumber-service
  labels:
    app: primenumber-service
spec:
  ports:
  - port: 9080
    name: 9080-tcp
    targetPort: 9080
  selector:
    app: primenumber-service
